// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/cache.proto

package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MyBlock struct {
	Block                []byte   `protobuf:"bytes,1,opt,name=block,proto3" json:"block,omitempty"`
	Offset               int64    `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MyBlock) Reset()         { *m = MyBlock{} }
func (m *MyBlock) String() string { return proto.CompactTextString(m) }
func (*MyBlock) ProtoMessage()    {}
func (*MyBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_cache_5729364da8df5825, []int{0}
}
func (m *MyBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MyBlock.Unmarshal(m, b)
}
func (m *MyBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MyBlock.Marshal(b, m, deterministic)
}
func (dst *MyBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MyBlock.Merge(dst, src)
}
func (m *MyBlock) XXX_Size() int {
	return xxx_messageInfo_MyBlock.Size(m)
}
func (m *MyBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_MyBlock.DiscardUnknown(m)
}

var xxx_messageInfo_MyBlock proto.InternalMessageInfo

func (m *MyBlock) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

func (m *MyBlock) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*MyBlock)(nil), "server.MyBlock")
}

func init() { proto.RegisterFile("server/cache.proto", fileDescriptor_cache_5729364da8df5825) }

var fileDescriptor_cache_5729364da8df5825 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x4f, 0x4e, 0x4c, 0xce, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x83, 0x88, 0x29, 0x99, 0x73, 0xb1, 0xfb, 0x56, 0x3a, 0xe5, 0xe4, 0x27, 0x67, 0x0b, 0x89, 0x70,
	0xb1, 0x26, 0x81, 0x18, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x3c, 0x41, 0x10, 0x8e, 0x90, 0x18, 0x17,
	0x5b, 0x7e, 0x5a, 0x5a, 0x71, 0x6a, 0x89, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x94, 0x97,
	0xc4, 0x06, 0x36, 0xc7, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xef, 0x1a, 0x6c, 0x5d, 0x00,
	0x00, 0x00,
}
